version: '3.8'

services:
  mysql_auth:
    container_name: auth-mysql-db-container
    image: mysql:8.1.0
    env_file: .env.db.dev
    ports:
      - '3306:3306'
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3306']
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 1s
  server_auth:
    container_name: auth-server-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env.db.dev
    environment:
      NODE_ENV: development
      PORT: 5000
    volumes:
      - .:/usr/server
      - /usr/server/node_modules
    ports:
      - '5000:5000'
    tty: true
    depends_on:
      mysql_auth:
        condition: service_healthy
        restart: true
    restart: always

volumes:
  auth-server:
