version: '3.8'

services:
  server:
    container_name: auth-server-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 5000
    volumes:
      - .:/usr/server
      - /usr/server/node_modules
    ports:
      - '5000:5000'
    tty: true
  mysql:
    container_name: auth-mysql-db-container
    image: mysql:8.1.0
    env_file: .env.db.dev
    volumes:
      - auth-server:/usr/server
    ports:
      - '3306:3306'

volumes:
  auth-server:
